import { useState } from "react";
import { BarChart3, CalendarDays, ChevronLeft, ChevronRight, Package, Plus, ShoppingCart, Truck, Wallet, ArrowDownToLine, ArrowUpFromLine } from "lucide-react";
import { useStore } from "@/lib/store";
import { brl, dateOnly, dateTime } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Cash={open:boolean;openedAt:string;opening:number;withdrawals:number;additions:number;closedAt?:string;counted?:number};
type PurchaseLine={productId:string;productName:string;color:string;size:string;quantity:number;cost:number};
type Purchase={id:string;date:string;supplier:string;total:number;status:"recebida"|"pendente";notes:string;items:PurchaseLine[]};
type Supplier={id:string;name:string;phone:string;contact:string};
type Event={id:string;date:string;title:string;type:"Aniversário"|"Feriado"|"Promoção"|"Importante";notes:string};

function usePersisted<T>(key:string,initial:T){
  const [value,setValue]=useState<T>(()=>{if(typeof window==="undefined")return initial;try{return JSON.parse(window.localStorage.getItem(key)||"null")??initial}catch{return initial}});
  const save=(next:T)=>{setValue(next);if(typeof window!=="undefined")window.localStorage.setItem(key,JSON.stringify(next))};
  return [value,save] as const;
}

const tabs=[["caixa","Caixa",Wallet],["estoque","Estoque",Package],["movimentacoes","Movimentações",ArrowDownToLine],["compras","Compras",ShoppingCart],["fornecedores","Fornecedores",Truck],["relatorios","Relatórios",BarChart3],["eventos","Agenda",CalendarDays]] as const;

export function OperationsSection(){
  const [tab,setTab]=useState<(typeof tabs)[number][0]>("caixa");
  return <div className="space-y-4"><div className="flex gap-2 overflow-x-auto rounded-2xl border bg-card p-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={"flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-medium "+(tab===id?"bg-primary text-primary-foreground":"hover:bg-muted")}><Icon className="h-4 w-4"/>{label}</button>)}</div>
    {tab==="caixa"&&<CashTab/>}{tab==="estoque"&&<StockTab/>}{tab==="movimentacoes"&&<StockMovementsTab/>}{tab==="compras"&&<PurchasesTab/>}{tab==="fornecedores"&&<SuppliersTab/>}{tab==="relatorios"&&<ReportsTab/>}{tab==="eventos"&&<EventsTab/>}
  </div>;
}

function CashTab(){
  const {sales}=useStore(); const [cash,setCash]=usePersisted<Cash>("modah:cash",{open:false,openedAt:"",opening:0,withdrawals:0,additions:0}); const [opening,setOpening]=useState(""); const [counted,setCounted]=useState("");
  const today=new Date().toISOString().slice(0,10); const todaySales=sales.filter(s=>s.date.slice(0,10)===today); const received=todaySales.reduce((n,s)=>n+s.amountPaid,0); const expected=cash.opening+cash.additions+received-cash.withdrawals;
  const byMethod=Object.entries(todaySales.reduce<Record<string,number>>((a,s)=>{a[s.paymentMethod]=(a[s.paymentMethod]||0)+s.amountPaid;return a},{}));
  const open=()=>{const n=Number(opening)||0;if(n<0)return;setCash({open:true,openedAt:new Date().toISOString(),opening:n,withdrawals:0,additions:0});setOpening("")};
  return <section className="card-elevated rounded-2xl p-4 space-y-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Caixa</h2><p className="text-sm text-muted-foreground">Abertura, recebimentos, sangrias, suprimentos e fechamento.</p></div><span className={"rounded-full px-3 py-1 text-xs font-semibold "+(cash.open?"bg-success/15 text-success":"bg-muted")}>{cash.open?"Caixa aberto":"Caixa fechado"}</span></div>
    {!cash.open?<div className="flex max-w-sm gap-2"><Input type="number" min="0" placeholder="Troco inicial (R$)" value={opening} onChange={e=>setOpening(e.target.value)}/><Button onClick={open}>Abrir caixa</Button></div>:<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Abertura",cash.opening],["Recebido hoje",received],["Saídas",cash.withdrawals],["Esperado",expected]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">{l}</p><b className="text-xl">{brl(Number(v))}</b></div>)}</div>
    <div className="grid gap-3 sm:grid-cols-2"><Button variant="outline" onClick={()=>{const v=Number(prompt("Valor da sangria:"))||0;if(v>0)setCash({...cash,withdrawals:cash.withdrawals+v})}}>Registrar sangria</Button><Button variant="outline" onClick={()=>{const v=Number(prompt("Valor do suprimento:"))||0;if(v>0)setCash({...cash,additions:cash.additions+v})}}>Registrar suprimento</Button></div>
    <div className="rounded-xl border p-4"><h3 className="mb-3 font-semibold">Vendas por pagamento</h3>{byMethod.length?<div className="space-y-2">{byMethod.map(([m,v])=><div key={m} className="flex justify-between text-sm"><span>{m}</span><b>{brl(v)}</b></div>)}</div>:<p className="text-sm text-muted-foreground">Nenhuma venda hoje.</p>}</div>
    <div className="flex gap-2"><Input type="number" min="0" placeholder="Valor contado" value={counted} onChange={e=>setCounted(e.target.value)}/><Button onClick={()=>{const n=Number(counted)||0;setCash({...cash,open:false,closedAt:new Date().toISOString(),counted:n});setCounted("")}}>Fechar caixa</Button></div>
    {cash.closedAt&&<p className="text-sm">Último fechamento: contado {brl(cash.counted||0)} · diferença {brl((cash.counted||0)-expected)}</p>}</>}
  </section>;
}

function StockTab(){
  const {products,restock}=useStore(); const [filter,setFilter]=useState(""); const low=products.filter(p=>p.variations.reduce((n,v)=>n+v.qty,0)<=p.minStock); const rows=products.filter(p=>p.name.toLowerCase().includes(filter.toLowerCase()));
  return <section className="card-elevated rounded-2xl p-4"><div className="mb-4 flex flex-wrap items-end gap-3"><div className="min-w-64"><Label>Buscar produto</Label><Input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Nome..."/></div><div className="rounded-xl bg-danger/10 px-3 py-2 text-sm font-semibold text-danger">{low.length} com estoque baixo</div></div><Table><TableHeader><TableRow><TableHead>Produto</TableHead><TableHead>Variação</TableHead><TableHead>Estoque</TableHead><TableHead>Mínimo</TableHead><TableHead>Ação</TableHead></TableRow></TableHeader><TableBody>{rows.flatMap(p=>p.variations.map(v=><TableRow key={p.id+v.color+v.size}><TableCell>{p.name}</TableCell><TableCell>{v.color} / {v.size}</TableCell><TableCell className={v.qty<=p.minStock?"font-bold text-danger":""}>{v.qty}</TableCell><TableCell>{p.minStock}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>{const q=Number(prompt("Quantidade de entrada:"))||0;if(q>0)restock(p.id,v.color,v.size,q)}}><Plus className="h-3 w-3"/> Entrada</Button></TableCell></TableRow>))}</TableBody></Table></section>;
}

function StockMovementsTab(){
  const {stockMovements}=useStore(); const [filter,setFilter]=useState("");
  const rows=stockMovements.filter(m=>!filter||[m.productName,m.color,m.size,m.type,m.note].join(" ").toLowerCase().includes(filter.toLowerCase())).slice(0,200);
  return <section className="card-elevated rounded-2xl p-4"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-bold">Histórico de movimentações</h2><p className="text-sm text-muted-foreground">Entradas, vendas, trocas, devoluções e ajustes.</p></div><Input className="max-w-xs" placeholder="Filtrar..." value={filter} onChange={e=>setFilter(e.target.value)}/></div><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Tipo</TableHead><TableHead>Produto</TableHead><TableHead>Variação</TableHead><TableHead>Quantidade</TableHead><TableHead>Observação</TableHead></TableRow></TableHeader><TableBody>{rows.map(m=><TableRow key={m.id}><TableCell>{dateTime(m.date)}</TableCell><TableCell>{m.type}</TableCell><TableCell>{m.productName}</TableCell><TableCell>{m.color}/{m.size}</TableCell><TableCell className={m.quantity<0?"text-danger font-semibold":"text-success font-semibold"}>{m.quantity>0?"+"+m.quantity:m.quantity}</TableCell><TableCell>{m.note}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="py-8 text-center text-sm text-muted-foreground">Nenhuma movimentação encontrada.</p>}</section>;
}

function PurchasesTab(){
  const {products,restock,updateProduct}=useStore(); const [purchases,setPurchases]=usePersisted<Purchase[]>("modah:purchases",[]); const [supplier,setSupplier]=useState(""); const [notes,setNotes]=useState(""); const [productId,setProductId]=useState(""); const [variation,setVariation]=useState(""); const [qty,setQty]=useState(1); const [cost,setCost]=useState("");
  const [lines,setLines]=useState<PurchaseLine[]>([]);
  const product=products.find(p=>p.id===productId); const selected=product?.variations.find(v=>v.color+"|"+v.size===variation);
  const addLine=()=>{if(!product||!selected||qty<1||Number(cost)<=0)return;const key=product.id+"|"+selected.color+"|"+selected.size;const old=lines.find(l=>l.productId+"|"+l.color+"|"+l.size===key);setLines(old?lines.map(l=>l===old?{...l,quantity:l.quantity+qty,cost:Number(cost)}:l):[...lines,{productId:product.id,productName:product.name,color:selected.color,size:selected.size,quantity:qty,cost:Number(cost)}]);setProductId("");setVariation("");setQty(1);setCost("")};
  const total=lines.reduce((n,l)=>n+l.quantity*l.cost,0);
  const add=()=>{if(!supplier||!lines.length)return;const record={id:crypto.randomUUID(),date:new Date().toISOString(),supplier,total,status:"recebida" as const,notes,items:lines};lines.forEach(l=>{restock(l.productId,l.color,l.size,l.quantity,"Compra de "+supplier);const p=products.find(x=>x.id===l.productId);if(p)updateProduct(p.id,{details:{...(p.details||{barcode:"",unit:"UN",cost:0,margin:0,wholesale:0,group:p.category,subgroup:"",supplier:"",warranty:"",brand:"",reference:"",validity:"",commission:0,location:"",hasGrid:false,notes:"",stock:0,inactive:false}),cost:l.cost,supplier}})});setPurchases([record,...purchases]);setSupplier("");setNotes("");setLines([])};
  return <section className="card-elevated rounded-2xl p-4 space-y-4"><div><h2 className="font-bold">Compras de mercadoria</h2><p className="text-sm text-muted-foreground">Registre itens da compra e aumente o estoque automaticamente.</p></div>
    <div className="grid gap-3 md:grid-cols-4"><Input placeholder="Fornecedor" value={supplier} onChange={e=>setSupplier(e.target.value)}/><Input placeholder="Observações" value={notes} onChange={e=>setNotes(e.target.value)}/><div className="rounded-xl bg-muted p-3 text-sm">Total da compra: <b>{brl(total)}</b></div><Button disabled={!supplier||!lines.length} onClick={add}>Registrar compra</Button></div>
    <div className="rounded-xl border p-4"><h3 className="mb-3 font-semibold">Adicionar item</h3><div className="grid gap-3 sm:grid-cols-[1.2fr_1fr_90px_120px_auto] sm:items-end"><div><Label>Produto</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={productId} onChange={e=>{setProductId(e.target.value);setVariation("")}}><option value="">Selecione...</option>{products.filter(p=>!p.details?.inactive).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div><Label>Cor / tamanho</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={variation} onChange={e=>setVariation(e.target.value)} disabled={!product}><option value="">Selecione...</option>{product?.variations.map(v=><option key={v.color+"|"+v.size} value={v.color+"|"+v.size}>{v.color}/{v.size}</option>)}</select></div><div><Label>Qtd.</Label><Input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/></div><div><Label>Custo unitário</Label><Input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></div><Button onClick={addLine}><Plus className="h-4 w-4"/>Adicionar</Button></div></div>
    {lines.length>0&&<Table><TableHeader><TableRow><TableHead>Produto</TableHead><TableHead>Variação</TableHead><TableHead>Qtd.</TableHead><TableHead>Custo</TableHead><TableHead>Total</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{lines.map((l,i)=><TableRow key={i}><TableCell>{l.productName}</TableCell><TableCell>{l.color}/{l.size}</TableCell><TableCell>{l.quantity}</TableCell><TableCell>{brl(l.cost)}</TableCell><TableCell>{brl(l.cost*l.quantity)}</TableCell><TableCell><Button size="icon" variant="ghost" onClick={()=>setLines(lines.filter((_,idx)=>idx!==i))}><Plus className="h-4 w-4 rotate-45"/></Button></TableCell></TableRow>)}</TableBody></Table>}
    <Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Fornecedor</TableHead><TableHead>Itens</TableHead><TableHead>Total</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{purchases.map(p=><TableRow key={p.id}><TableCell>{dateOnly(p.date)}</TableCell><TableCell>{p.supplier}</TableCell><TableCell>{p.items?.reduce((n,l)=>n+l.quantity,0)??0} un.</TableCell><TableCell>{brl(p.total)}</TableCell><TableCell>{p.status}</TableCell></TableRow>)}</TableBody></Table>
  </section>;
}

function SuppliersTab(){
  const [items,setItems]=usePersisted<Supplier[]>("modah:suppliers",[]); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [contact,setContact]=useState("");
  const add=()=>{if(!name.trim())return;setItems([{id:crypto.randomUUID(),name,phone,contact},...items]);setName("");setPhone("");setContact("")};
  return <section className="card-elevated rounded-2xl p-4 space-y-4"><h2 className="font-bold">Fornecedores</h2><div className="grid gap-2 md:grid-cols-4"><Input placeholder="Fornecedor" value={name} onChange={e=>setName(e.target.value)}/><Input placeholder="Telefone" value={phone} onChange={e=>setPhone(e.target.value)}/><Input placeholder="Contato" value={contact} onChange={e=>setContact(e.target.value)}/><Button onClick={add}>Cadastrar</Button></div><Table><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>Telefone</TableHead><TableHead>Contato</TableHead></TableRow></TableHeader><TableBody>{items.map(x=><TableRow key={x.id}><TableCell>{x.name}</TableCell><TableCell>{x.phone}</TableCell><TableCell>{x.contact}</TableCell></TableRow>)}</TableBody></Table></section>;
}

function ReportsTab(){
  const {sales,products,customers}=useStore(); const [start,setStart]=useState(""); const [end,setEnd]=useState("");
  const filtered=sales.filter(s=>(!start||s.date.slice(0,10)>=start)&&(!end||s.date.slice(0,10)<=end)); const sold=filtered.reduce((n,s)=>n+s.items.reduce((a,i)=>a+i.quantity,0),0); const revenue=filtered.reduce((n,s)=>n+s.total,0); const received=filtered.reduce((n,s)=>n+s.amountPaid,0); const cost=filtered.reduce((n,s)=>n+s.items.reduce((a,i)=>a+(products.find(p=>p.id===i.productId)?.details?.cost||0)*i.quantity,0),0); const stock=products.reduce((n,p)=>n+p.variations.reduce((a,v)=>a+v.qty,0),0); const low=products.filter(p=>p.variations.reduce((a,v)=>a+v.qty,0)<=p.minStock); const lastSale=new Map<string,string>(); sales.forEach(s=>s.items.forEach(i=>lastSale.set(i.productId, s.date))); const stuck=products.filter(p=>p.variations.reduce((n,v)=>n+v.qty,0)>0 && (!lastSale.get(p.id) || (Date.now()-new Date(lastSale.get(p.id)!).getTime())>30*864e5)).sort((a,b)=>(lastSale.get(a.id)||"").localeCompare(lastSale.get(b.id)||""));
  const uniqueCustomers=new Set(filtered.map(s=>s.customerId).filter(Boolean)).size; const ticket=filtered.length?revenue/filtered.length:0;
  return <section className="space-y-4"><div className="card-elevated rounded-2xl p-4"><div className="flex flex-wrap items-end gap-3"><div><Label>De</Label><Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div><Label>Até</Label><Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><Button variant="outline" onClick={()=>{setStart("");setEnd("")}}>Todo o período</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Faturamento",brl(revenue)],["Recebido",brl(received)],["Custo estimado",brl(cost)],["Lucro bruto",brl(revenue-cost)]].map(([a,b])=><div key={a} className="card-elevated rounded-2xl p-4"><p className="text-xs text-muted-foreground">{a}</p><b className="text-xl">{b}</b></div>)}</div>
    <div className="grid gap-3 sm:grid-cols-4"><div className="card-elevated rounded-2xl p-4">Vendas <b>{filtered.length}</b></div><div className="card-elevated rounded-2xl p-4">Peças <b>{sold}</b></div><div className="card-elevated rounded-2xl p-4">Clientes <b>{uniqueCustomers}</b></div><div className="card-elevated rounded-2xl p-4">Ticket médio <b>{brl(ticket)}</b></div></div>
    <div className="card-elevated rounded-2xl p-4"><h2 className="mb-3 font-bold">Estoque baixo</h2>{low.length?<ul className="space-y-2">{low.map(p=><li key={p.id} className="flex justify-between rounded-xl bg-muted p-3 text-sm"><span>{p.name}</span><b>{p.variations.reduce((n,v)=>n+v.qty,0)} un.</b></li>)}</ul>:<p className="text-sm text-muted-foreground">Nenhum produto abaixo do mínimo.</p>}</div><div className="card-elevated rounded-2xl p-4"><h2 className="mb-3 font-bold">Produtos encalhados</h2>{stuck.length?<ul className="space-y-2">{stuck.slice(0,10).map(p=>{const last=lastSale.get(p.id);const days=last?Math.floor((Date.now()-new Date(last).getTime())/864e5):null;return <li key={p.id} className="flex justify-between rounded-xl bg-muted p-3 text-sm"><span>{p.name}<span className="ml-2 text-xs text-muted-foreground">{days===null?"Nunca vendido":days+" dias sem venda"}</span></span><b>{p.variations.reduce((n,v)=>n+v.qty,0)} un.</b></li>})}</ul>:<p className="text-sm text-muted-foreground">Nenhum produto encalhado há mais de 30 dias.</p>}</div>
  </section>;
}

function EventsTab(){
  const {customers}=useStore(); const [items,setItems]=usePersisted<Event[]>("modah:events",[]); const [cursor,setCursor]=useState(()=>new Date()); const [date,setDate]=useState(""); const [title,setTitle]=useState(""); const [type,setType]=useState<Event["type"]>("Importante"); const [notes,setNotes]=useState("");
  const year=cursor.getFullYear();const month=cursor.getMonth();const days=new Date(year,month+1,0).getDate();const offset=(new Date(year,month,1).getDay()+6)%7;const monthName=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(cursor);const monthKey=year+"-"+String(month+1).padStart(2,"0");
  const birthdays=customers.filter(c=>c.birthDate).map(c=>({id:"birthday-"+c.id,date:monthKey+"-"+c.birthDate.slice(8,10),title:"Aniversário de "+c.name,type:"Aniversário" as const,notes:"Cliente cadastrado"})); const monthEvents=[...items.filter(e=>e.date.slice(0,7)===monthKey),...birthdays];
  const dayEvents=(day:number)=>monthEvents.filter(e=>e.date.slice(8,10)===String(day).padStart(2,"0")); const add=()=>{if(!date||!title)return;setItems([...items,{id:crypto.randomUUID(),date,title,type,notes}].sort((a,b)=>a.date.localeCompare(b.date)));setDate("");setTitle("");setNotes("")}; const openBirthday=(e:Event)=>{const c=customers.find(c=>e.id==="birthday-"+c.id);if(c)window.dispatchEvent(new CustomEvent("modah:open-customer",{detail:c.id}))};
  return <section className="space-y-4"><div className="card-elevated rounded-2xl p-4"><div className="mb-4 flex items-center justify-between"><Button variant="outline" size="icon" onClick={()=>setCursor(new Date(year,month-1,1))}><ChevronLeft className="h-4 w-4"/></Button><h2 className="capitalize text-lg font-bold">{monthName}</h2><Button variant="outline" size="icon" onClick={()=>setCursor(new Date(year,month+1,1))}><ChevronRight className="h-4 w-4"/></Button></div><div className="grid grid-cols-7 border-l border-t text-xs">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(d=><div key={d} className="border-b border-r bg-muted p-2 text-center font-semibold">{d}</div>)}{Array.from({length:offset}).map((_,i)=><div key={"e"+i} className="min-h-24 border-b border-r bg-muted/30"/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><div key={d} className="min-h-24 border-b border-r p-2"><div className="mb-1 text-right font-semibold">{d}</div><div className="space-y-1">{dayEvents(d).map(e=><button key={e.id} onClick={()=>openBirthday(e)} className={"w-full rounded-md px-2 py-1 text-left text-[11px] "+(e.type==="Aniversário"?"bg-warning/15 text-warning":"bg-primary/10 text-primary")}>{e.title}</button>)}</div></div>)}</div></div>
    <div className="card-elevated rounded-2xl p-4 space-y-4"><div><h2 className="font-bold">Adicionar evento</h2><p className="text-sm text-muted-foreground">Eventos personalizados ficam salvos no calendário.</p></div><div className="grid gap-2 md:grid-cols-5"><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/><Input placeholder="Título" value={title} onChange={e=>setTitle(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3" value={type} onChange={e=>setType(e.target.value as Event["type"])}>{["Aniversário","Feriado","Promoção","Importante"].map(x=><option key={x}>{x}</option>)}</select><Input placeholder="Observações" value={notes} onChange={e=>setNotes(e.target.value)}/><Button onClick={add}>Adicionar evento</Button></div></div>
    <div className="card-elevated rounded-2xl p-4"><h3 className="mb-3 font-bold">Eventos do mês</h3>{monthEvents.length?<Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Tipo</TableHead><TableHead>Evento</TableHead><TableHead>Observações</TableHead></TableRow></TableHeader><TableBody>{monthEvents.sort((a,b)=>a.date.localeCompare(b.date)).map(e=><TableRow key={e.id} className={e.type==="Aniversário"?"cursor-pointer":""} onClick={()=>openBirthday(e)}><TableCell>{dateOnly(e.date)}</TableCell><TableCell>{e.type}</TableCell><TableCell className={e.type==="Aniversário"?"font-medium text-primary":""}>{e.title}</TableCell><TableCell>{e.notes}</TableCell></TableRow>)}</TableBody></Table>:<p className="text-sm text-muted-foreground">Nenhum evento neste mês.</p>}</div>
  </section>;
}
